// Mocks generated by Mockito 5.1.0 from annotations
// in payu_terms_and_conditions/test/src/terms_and_conditions_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:payu_core/payu_core.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [PayuLauncher].
///
/// See the documentation for Mockito's code generation for more information.
class MockPayuLauncher extends _i1.Mock implements _i2.PayuLauncher {
  MockPayuLauncher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> call(String? number) =>
      (super.noSuchMethod(Invocation.method(#call, [number]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> launch(String? uri) =>
      (super.noSuchMethod(Invocation.method(#launch, [uri]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}
