// Mocks generated by Mockito 5.4.0 from annotations
// in payu_three_ds/test/src/soft_accept/soft_accept_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:payu_three_ds/src/soft_accept/helpers/soft_accept_query_parameter_extractor.dart'
    as _i5;
import 'package:payu_three_ds/src/soft_accept/network/client/soft_accept_network_client.dart'
    as _i2;
import 'package:payu_three_ds/src/soft_accept/network/models/soft_accept_log.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SoftAcceptNetworkClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoftAcceptNetworkClient extends _i1.Mock
    implements _i2.SoftAcceptNetworkClient {
  MockSoftAcceptNetworkClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> postSoftAcceptLog(_i4.SoftAcceptLog? log) =>
      (super.noSuchMethod(
        Invocation.method(
          #postSoftAcceptLog,
          [log],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [SoftAcceptQueryParameterExtractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoftAcceptQueryParameterExtractor extends _i1.Mock
    implements _i5.SoftAcceptQueryParameterExtractor {
  MockSoftAcceptQueryParameterExtractor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String? extractAuthenticationId(String? uri) =>
      (super.noSuchMethod(Invocation.method(
        #extractAuthenticationId,
        [uri],
      )) as String?);
}
