// Mocks generated by Mockito 5.1.0 from annotations
// in payu_payment_methods/test/src/features/payment_methods/payment_methods_page_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:payu_core/payu_core.dart' as _i2;
import 'package:payu_payment_methods/src/features/core/payment_methods_item.dart'
    as _i9;
import 'package:payu_payment_methods/src/features/core/payment_methods_platform_provider.dart'
    as _i5;
import 'package:payu_payment_methods/src/features/core/payment_methods_storage.dart'
    as _i7;
import 'package:payu_payment_methods/src/features/payment_methods/payment_methods_controller.dart'
    as _i4;
import 'package:payu_payment_methods/src/features/payment_methods/payment_methods_listener.dart'
    as _i6;
import 'package:payu_payment_methods/src/payment_methods_configuration.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeBrandImageProvider_0 extends _i1.Fake
    implements _i2.BrandImageProvider {}

/// A class which mocks [PaymentMethodsConfiguration].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentMethodsConfiguration extends _i1.Mock
    implements _i3.PaymentMethodsConfiguration {
  MockPaymentMethodsConfiguration() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.CardToken> get cardTokens =>
      (super.noSuchMethod(Invocation.getter(#cardTokens),
          returnValue: <_i2.CardToken>[]) as List<_i2.CardToken>);
  @override
  List<_i2.PayByLink> get payByLinks =>
      (super.noSuchMethod(Invocation.getter(#payByLinks),
          returnValue: <_i2.PayByLink>[]) as List<_i2.PayByLink>);
  @override
  bool get enableAddCard =>
      (super.noSuchMethod(Invocation.getter(#enableAddCard), returnValue: false)
          as bool);
  @override
  bool get enablePayByLinks =>
      (super.noSuchMethod(Invocation.getter(#enablePayByLinks),
          returnValue: false) as bool);
}

/// A class which mocks [PaymentMethodsControllerDelegate].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentMethodsControllerDelegate extends _i1.Mock
    implements _i4.PaymentMethodsControllerDelegate {
  MockPaymentMethodsControllerDelegate() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didComplete(_i2.PaymentMethod? paymentMethod) =>
      super.noSuchMethod(Invocation.method(#didComplete, [paymentMethod]),
          returnValueForMissingStub: null);
  @override
  void navigateToBankTransfer() =>
      super.noSuchMethod(Invocation.method(#navigateToBankTransfer, []),
          returnValueForMissingStub: null);
  @override
  void navigateToCardToken() =>
      super.noSuchMethod(Invocation.method(#navigateToCardToken, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [PaymentMethodPlatformProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentMethodPlatformProvider extends _i1.Mock
    implements _i5.PaymentMethodPlatformProvider {
  MockPaymentMethodPlatformProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isAndroid() =>
      (super.noSuchMethod(Invocation.method(#isAndroid, []), returnValue: false)
          as bool);
  @override
  bool isiOS() =>
      (super.noSuchMethod(Invocation.method(#isiOS, []), returnValue: false)
          as bool);
}

/// A class which mocks [PaymentMethodsListener].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentMethodsListener extends _i1.Mock
    implements _i6.PaymentMethodsListener {
  MockPaymentMethodsListener() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didDeletePaymentMethod(_i2.PaymentMethod? paymentMethod) => super
      .noSuchMethod(Invocation.method(#didDeletePaymentMethod, [paymentMethod]),
          returnValueForMissingStub: null);
}

/// A class which mocks [PaymentMethodsStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentMethodsStorage extends _i1.Mock
    implements _i7.PaymentMethodsStorage {
  MockPaymentMethodsStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String?> getSelectedPaymentMethodHash() =>
      (super.noSuchMethod(Invocation.method(#getSelectedPaymentMethodHash, []),
          returnValue: Future<String?>.value()) as _i8.Future<String?>);
  @override
  _i8.Future<void> saveSelectedPaymentMethodHash(String? hash) => (super
      .noSuchMethod(Invocation.method(#saveSelectedPaymentMethodHash, [hash]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
}

/// A class which mocks [PaymentMethodsItem].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentMethodsItem extends _i1.Mock
    implements _i9.PaymentMethodsItem {
  MockPaymentMethodsItem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get enabled =>
      (super.noSuchMethod(Invocation.getter(#enabled), returnValue: false)
          as bool);
  @override
  String get title =>
      (super.noSuchMethod(Invocation.getter(#title), returnValue: '')
          as String);
  @override
  _i2.BrandImageProvider get brandImageProvider =>
      (super.noSuchMethod(Invocation.getter(#brandImageProvider),
          returnValue: _FakeBrandImageProvider_0()) as _i2.BrandImageProvider);
  @override
  double get brandImageProviderSize =>
      (super.noSuchMethod(Invocation.getter(#brandImageProviderSize),
          returnValue: 0.0) as double);
}
